### ISSUE TITLE
Applet won't start and keeps pushing errors

### ISSUE THREAD

**Issue by alexismo** [sagetarian/skype-wrapper#60]
Started skype-wrapper via the alt+f2 command. It keeps pushing the same error to my compiz output:

``` bash
(indicator-applet-skype.py:13473): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
```

**Comment by grissir** [comment]
Can you specify the ubuntu version you are on?

**Comment by alexismo** [comment]
Ubuntu 12.04. uname-a --> `Linux a-laptop 3.2.0-24-generic-pae #38-Ubuntu SMP Tue May 1 16:40:26 UTC 2012 i686 i686 i386 GNU/Linux`

**Comment by grissir** [comment]
Which favour of ubuntu are you using

**Comment by alexismo** [comment]
I don't know how else to put it...
I'm using Ubuntu 12.04 Precise Pangolin standard installation.
Are there any commands you'd like me to run?

**Comment by grissir** [comment]
no I just don't understand the error :(
but it may help us if you install dconf-editor and look up all the things in apps/skype-wrapper espacially debug-level

**Comment by alexismo** [comment]
I changed the debug-level to 3. Here is what I get.

```
(indicator-applet-skype.py:12591): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(indicator-applet-skype.py:12610): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(indicator-applet-skype.py:12629): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(indicator-applet-skype.py:12649): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(indicator-applet-skype.py:12668): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(indicator-applet-skype.py:12687): GLib-GIO-ERROR **: Settings schema 'apps.skype-wrapper' does not contain a key named 'debug-level'
Applet closed
API crash detected
Restarting skype-wrapper
^CTraceback (most recent call last):
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 89, in <module>
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 64, in start_skype
    start_skype()
  File "/usr/share/skype-wrapper/skype-wrapper.py", line 55, in start_skype
    ret = subprocess.call(['python','indicator-applet-skype.py'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1291, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
```

**Comment by grissir** [comment]
The problem is that skype-wrapper can't find the gsettings for skype wrapper

**Comment by grissir** [comment]
which version of skype-wrapper do you use?

**Comment by alexismo** [comment]
`0ubuntu6.2.2~precise3` I'm using the version from the PPA.

**Comment by grissir** [comment]
Can you try to delete this file first /usr/share/glib-2.0/schemas/apps.skype-wrapper.gschema.xml
and then install the version from https://launchpad.net/~skype-wrapper/+archive/unstable when the new package is build

**Comment by grissir** [comment]
Hi
is it working currently, please note that the stable ppa is now ahead of the unstable
Just trying to do some cleaning and wanted to know if the bug still exists

**Comment by zevilz** [comment]
I have this problem on Debian 8 from https://github.com/sagetarian/skype-wrapper/tree/master/skype-wrapper.

From PPA not working and crashing with

> Traceback (most recent call last):
> File "/usr/share/skype-wrapper/skype-wrapper.py", line 45, in <module>
> import helpers
> File "/usr/share/skype-wrapper/helpers.py", line 34, in <module>
> import pynotify
> File "/usr/lib/python2.7/dist-packages/gtk-2.0/pynotify/**init**.py", line 1, in <module>
> from _pynotify import *
> ImportError: could not import gobject (could not find _PyGObject_API object)[/code]
