### ISSUE TITLE
indicator-applet-skype.py crashed with ISkypeError in _DoCommand(): [Errno 68]

### ISSUE THREAD

**Issue by haeckle** [sagetarian/skype-wrapper#70]
When I start skype-wrapper the skype-confirmation-window to allow the access by skype-wrapper pops several times up and when I try to open skype via the message-indicator skype-wrapper itself crashes.

my system:
Ubuntu 12.04 (Linux 3.2.0-29-generic x86_64)
skype-wrapper 0ubuntu6.4.0~precise0
python 2.7
skype 4.0.0.8-0oneiric1

**Comment by stonerl** [comment]
After you accepted Skype4Py does it work?

**Comment by haeckle** [comment]
It does start working otherwise there wouldn't be an entry in the message-indicator-menu. But the confirmation-window pops up several times (in my last try it was 3 times, but previously it keeps up pushing new pop ups till I stopped it via killall).

**Comment by stonerl** [comment]
This happen only on the first run, right? After confirmed it and restart the wrapper you shouldn't see any Request Window.

I tested it but It only opens once on my system. Could you remove Skype4Py From the Public API list close Skype  start it from the terminal and check if it happens  again. If so could you post the output.

Did you tick mark "Remember this Selection"

**Comment by haeckle** [comment]
Hm. The last time the decision wasn't saved, even if I marked the "Remember this Selection".
This time I also marked it, but not only once but in all three pop ups (before I just confirmed one and quit the others).

Now I quit Skype and tried it again and now it works. The decision is saved and Skype opens when i invoke it from the message-indicator-menu.

Here is the output from the second try (when Skype4Py wasn't saved as allowed):

```
:~$ skype-wrapper
Starting skype-wrapper
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Starting Skype process
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
/usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so: falsche ELF-Klasse: ELFCLASS64

(skype:29913): Gtk-WARNING **: Failed to load type module: /usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so

/usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so: falsche ELF-Klasse: ELFCLASS64

(skype:29913): Gtk-WARNING **: Failed to load type module: /usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so

/usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so: falsche ELF-Klasse: ELFCLASS64

(skype:29913): Gtk-WARNING **: Failed to load type module: /usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so

/usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so: falsche ELF-Klasse: ELFCLASS64

(skype:29913): Gtk-WARNING **: Failed to load type module: /usr/lib/gtk-2.0/2.10.0/menuproxies/libappmenu.so

WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
WARNING: Failed to attach skype-wrapper to Skype process
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
INFO: Initializing Skype API
INFO: Waiting for Skype Process
INFO: Attaching skype-wrapper to Skype process
INFO: Attached complete
INFO: Initializing online status for users
INFO: Checking unread messages
INFO: Checking online status changing users
INFO: User *** is online
INFO: User *** is online
INFO: User *** is online
INFO: User Echo / Sound Test Service is online
INFO: Checking online presence
INFO: Checking file transfers
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 175, in on_click
    self.skype.skype.Client.Focus()
  File "/usr/lib/pymodules/python2.7/Skype4Py/client.py", line 93, in Focus
    self._Skype._DoCommand('FOCUS')
  File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 364, in _DoCommand
    raise ISkypeError(int(errnum), errstr)
Skype4Py.errors.ISkypeError: [Errno 68] 
INFO: Checking online presence
INFO: Check if Skype instance is running
INFO: Checking online presence
INFO: Check if Skype instance is running
```

**Comment by stonerl** [comment]
I think  this is a problem with Skype itself. Did you upgrade from Skype 2.2?

**Comment by haeckle** [comment]
I had skype 2.2 previously, but I don't remember if I unistalled it and did a "fresh" install of skape or if I just upgraded it.
Could possibly be a bug with skype itself. But what about these lines: 

```
Traceback (most recent call last):
  File "indicator-applet-skype.py", line 175, in on_click
    self.skype.skype.Client.Focus()
  File "/usr/lib/pymodules/python2.7/Skype4Py/client.py", line 93, in Focus
    self._Skype._DoCommand('FOCUS')
  File "/usr/lib/pymodules/python2.7/Skype4Py/skype.py", line 364, in _DoCommand
    raise ISkypeError(int(errnum), errstr)
Skype4Py.errors.ISkypeError: [Errno 68] 
```

That was when I tried to open skype via the message-indicator.

**Comment by stonerl** [comment]
Seems to be an internal Skype4py error. I assume it didn't open the Skype main window?

Could you test the following:

*rename the .Skype folder in you homefolder.
*start skype-wrapper again

this way you get a completely new skype-folder with no settings from Skype 2.2. If the multiple confirmation windows don't show up anymore it was because of some old Skype 2.2 settings.

**Comment by haeckle** [comment]
Totally forgot this bugreport. the multiple confirmation windowas are gone. I think it was a problem with the old skype 2.2 settings. As no one else seems to have the same problem I close this report.
