### ISSUE TITLE
Unknown module "shared"

### ISSUE THREAD

**Issue by alorence** [sagetarian/skype-wrapper#72]
Ubuntu 12.04
skype-wrapper all 0ubuntu6.5.2~precise1 from PPA

The script can't be launched. From console, the error is :

> skype-wrapper 
> Traceback (most recent call last):
>   File "/usr/share/skype-wrapper/skype-wrapper.py", line 45, in <module>
>     import helpers
>   File "/usr/share/skype-wrapper/helpers.py", line 34, in <module>
>     import shared
> ImportError: No module named shared

In install folder (/usr/share/skype-wrapper), in don't see any shared.py or shared.pyc.

**Comment by alorence** [comment]
Sorry, the bugs is not related to skype-wrapper but to the deb. Also, the issue already exists here : https://bugs.launchpad.net/skype-wrapper/+bug/1053228
